// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ITRC165$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ITRC165";
  readonly sourceName: "contracts/ITRC165.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes4","name":"interfaceID","type":"bytes4"}],"name":"supportsInterface","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/ITRC165.sol";
  readonly buildInfoId: "solc-0_8_28-558afe5f837087dd7984e8a579cf3a8f49ef6e05";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ITRC165"]: ITRC165$Type;
    ["contracts/ITRC165.sol:ITRC165"]: ITRC165$Type;
  }
}